# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempenjualan',
            name='fk_penjualan',
            field=models.ForeignKey(blank=True, db_column='fk_penjualan', null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.Penjualan'),
        ),
        migrations.AlterField(
            model_name='itempenjualan',
            name='fk_status_item_penjualan',
            field=models.ForeignKey(blank=True, db_column='fk_status_item_penjualan', null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.StatusItemPenjualan'),
        ),
    ]
